# docker-compose.yml
# Defines and runs the app container with volume persistence.

# version: "3.9"


services:
  db:
    image: postgres:16-alpine
    container_name: fastapi-postgres
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"   # optional, for external tools

  redis:
    image: redis:7-alpine
    container_name: fastapi-redis
    ports:
      - "6379:6379"


  app:
    build: .
    container_name: fastapi-crud-app
    ports:
      - "8000:8000"
    # volumes:
    #   # Persist SQLite database file
    #   - ./data:/app/data
    environment:
      # - DATABASE_URL=sqlite:///./data/test.db   # optional, we can use this if we change database.py
      DATABASE_URL: postgresql://appuser:apppassword@db:5432/appdb
      REDIS_URL: redis://redis:6379/0

    depends_on:
      - db
    command: sh -c "uv run alembic upgrade head && uv run uvicorn main:app --host 0.0.0.0 --port 8000"
volumes:
  postgres_data: